#2 add buttons
sasketeen/Everland-project pull request #17
Opened 2023-05-13 08:17 UTC by ksushw

2023-05-14 08:51 UTC, sasketeen requested changes

2023-05-14 08:51 UTC, sasketeen commented on src/blocks/link/link.scss
> +    &[disabled] {
у ссылок нет атрибута disabled. По идее ссылка вообще не может быть disabled, такое состояние есть только у кнопок. Спрошу потом у команды что они имели  в виду в макете под этим, а сейчас давай лучше в отдельный модификатор вынесем

2023-05-14 08:51 UTC, sasketeen commented on src/blocks/accardion-button/_opened/accardion-button_opened.scss
> +    background-color: #0C4BA0;
все цвета нужно будет заменить на соответствующие переменные

2023-05-14 08:51 UTC, sasketeen commented on src/blocks/accardion-button/accardion-button.scss
> +    transition: background-color 0.1s ease-out;
также написали миксин для транзишн, воспользуйся им. Есть тебе не подходит параметр all, то исправь миксин, добавь туда еще входной параметр того, что мы изменяем, и по дефолту пусть будет all, если ничего не передано

2023-05-14 09:51 UTC, sasketeen commented
Еще при слиянии есть конфликт. Его нужно решить

2023-05-15 08:16 UTC, sasketeen requested changes

2023-05-15 08:16 UTC, sasketeen commented on src/blocks/link/_color/link_color_white.scss
> +    &[disabled] {
пропустила тут несуществующий атрибут)

2023-05-15 08:16 UTC, sasketeen commented on src/blocks/accardion-button/accardion-button.scss
> +    &:hover {
на будущее. Я бы вообще поменял во всем проекте этот момент (я про него говорил, сегодня в чате вынесу это на обсуждение). Сейчас на телефонах при нажатии на какую-то кнопку у нее будет оставаться состояние ховера (эито особенность работы тачскрина). Чтобы это поправить, все стили для ховера можно вынести в специальный медиазапрос, проверяюший есть ли такое состояние на устройстве. Запихать его в миксин (больше миксинов богу миксинов) и использовать его по том везде где надо

Я у себя делал примерно вот так. В вашем случае нужно будет наверное немного изменить эту реализацию
```
@mixin hover($value: 0.7) {
  @media (hover: hover) { 
    transition: opacity 0.3s ease-out;
    &:hover { 
      opacity: $value;
    }
  }
}
```

В общем исправлять пока не надо, вкинул на подумать эту инфу, сегодня в чате предложу всем это реализовать) Возможно будет отдельная задача

2023-05-15 08:16 UTC, sasketeen commented on src/blocks/link/_disabled/link_disabled.scss
> +    color: #262626;
разве нету переменной под этот цвет? Если нет, то можешь добавть

2023-05-15 08:16 UTC, sasketeen commented on src/blocks/slider-button/slider-button.scss
> +            background-color: #262626;
аналогично

2023-05-15 08:16 UTC, sasketeen commented on src/blocks/accardion-button/accardion-button.scss
> +            background-color: #262626;
тут цвет остался напрямую написанный

2023-05-15 08:35 UTC, ksushw commented on src/blocks/accardion-button/accardion-button.scss
> +    &:hover {
+ хорошее решение))

2023-05-15 13:08 UTC, merged