#3
sasketeen/Everland-project pull request #28
Opened 2023-05-15 14:22 UTC by ksushw

2023-05-16 17:50 UTC, sasketeen requested changes

2023-05-16 17:50 UTC, sasketeen commented on src/index.html
> +              <button class="accordion__button"></button>
слабовидящий человек обычно использует скринридер для навигации по сайту. Скринридер читает текст внутри кнопки и человек понимает, что эта кнопка делает. В нашем случае кнопка без текста, соответственно сринридер просто прочитает "кнопка" и для чего она нужна будет непонятно. Для таких случаев есть специальный атрибут aria-label. Можешь прочитать про него на Доке или MDN

2023-05-16 17:50 UTC, sasketeen commented on src/index.html
> +        <template class="accordion__template">
Нам говорили, что теплейте должны находиться в внизу страницы, думаю вам тоже, поэтому при верстке секции убери его отсюда)

2023-05-16 17:50 UTC, sasketeen commented on src/index.html
> +              <h4 class="accordion__title">gfd</h4>
при верстке секции подумай над семантикой заголовков (обычно после h2 должен идти h3 и только потом h4). Пока не знаю что с этим делать...либо делать скрытый заголовок h2 либо оставить все как есть

2023-05-16 17:50 UTC, sasketeen commented on src/index.html
> +              <button class="accordion__button"></button>
плюс ты уже уже написали стили для кнопок, почему не применила?

2023-05-16 17:50 UTC, sasketeen commented on src/blocks/accordeon/accordion.scss
> +.accordion {
замечание в целом к аккордеону, а не к этой строчке: он отличается от макета. В частности вот как в макете на мобильной версии, и как у тебя
<img width="392" alt="image" src="https://github.com/sasketeen/Everland-project/assets/108020116/432f842d-8c2f-41a2-a97f-1f3a92503386">

<img width="498" alt="image" src="https://github.com/sasketeen/Everland-project/assets/108020116/c2a6d4bf-c71a-4ab1-bab8-a9bb8a9b753f">

2023-05-17 09:55 UTC, ksushw commented on src/index.html
> +              <h4 class="accordion__title">gfd</h4>
Сделал семантический тег h3. А ситуация такая: на дескнопной версии стили текста h4, а на мобилке и планшете h3

2023-05-17 12:41 UTC, sasketeen requested changes

2023-05-17 12:41 UTC, sasketeen commented on src/blocks/accordeon/accordion.scss
> +.accordion {
Аккордеон все еще отличается от макета (ну как минимум паддинги не совпадают очень сильно) Проверь пожалуйста стили на всех 3х разрешениях

2023-05-17 12:41 UTC, sasketeen commented on src/blocks/accordeon/_opened/accordion_opened.scss
> +.accordion_opened {
вообще в принципе давай определимся, ты пишешь стили для аккордеона в одном файле или в нескольких? Почему элементы блока у тебя написаны в файле аккордеона, а модификатор ты решила вынести? В принципе наверное на созвоне этот момент будем обсуждать, потому что все пишут по-разному, как я вижу.

2023-05-19 15:53 UTC, sasketeen requested changes
я тут поверхностно глянул, есть пара ошибок, как поправишь - я залью, и окончательно буду проверять уже в секции все)

2023-05-19 15:53 UTC, sasketeen commented on src/blocks/accordeon/_opened/accordion_opened.scss
> +        max-height: 150px;
очень плохая идея. А вдруг в аккордеоне будет много текста?Я примерно понимаю что это написано для плавной анимации раскрытия, но есть возможность обойтись без ограничения по высоте?

2023-05-19 15:53 UTC, sasketeen commented on src/index.html
> +      <section class="accordions section-container">
исправлять не надо, просто для справки, обычно пишут классы от общего к частному (по крайней мере меня так учили)...то есть сначала пишут общие обобщенные классы (section-container) и потом уже идут к более частным/локальным

2023-05-19 15:53 UTC, sasketeen commented on src/blocks/accordeon/_opened/accordion_opened.scss
> +.accordion_opened {
Баг. На мобилке аккордеон растягивается на всю ширину, но при это когда он раскатывается, то ширина его уменьшается 

<img width="299" alt="image" src="https://github.com/sasketeen/Everland-project/assets/108020116/5ce5636d-b26c-4b07-835d-01840f0246a0">

2023-05-19 15:53 UTC, sasketeen commented on src/blocks/accordeon/__button/accordion__button.scss
>      outline: unset;
Скорее всего из-за этой строчки я теперь при фокусе не вижу на каком элемент у меня фокус во время навигации через клаву. Ты либо должна переопределять дефолтный фокус, либо не затирать стили его (в основном при фокусе аутлайн как раз используется в браузерах)

2023-05-19 16:36 UTC, ksushw commented on src/blocks/accordeon/_opened/accordion_opened.scss
> +        max-height: 150px;
Я могу поставить 500px. Или 1000. Думаю что больше 1000 текст не займет.

2023-05-19 16:37 UTC, ksushw commented on src/blocks/accordeon/_opened/accordion_opened.scss
> +        max-height: 150px;
Для плавного появления обязательно нужно указывать в пикселях. Мин макс контент не работают с транзишн

2023-05-21 08:45 UTC, sasketeen approved these changes

2023-05-21 08:46 UTC, merged